export const START_RECEIVE_BOOKS = 'START_RECEIVE_BOOKS';
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';
export const ERROR_RECEIVE_BOOKS = 'ERROR_RECEIVE_BOOKS';

export const START_RECEIVE_BOOK = 'START_RECEIVE_BOOK';
export const RECEIVE_BOOK = 'RECEIVE_BOOK';
export const ERROR_RECEIVE_BOOK = 'ERROR_RECEIVE_BOOK';

export const DELETE_BOOK = 'DELETE_BOOK';
export const UNDO_DELETE_BOOK = 'UNDO_DELETE_BOOK';

export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';
